name = "Icarus"
license = "MIT"
licenselink = "//github.com/digitalcraftsman/hugo-icarus-theme/blob/master/LICENSE.md"
description = "A responsive and customizable hugo theme for bloggers."
homepage = "//github.com/pcanham/hugo-icarus-theme"
tags = ["syntax highlighting", "maxthjax", "rss", "gallery", "widgets", "google analytics"]
features = ["syntax highlighting", "maxthjax", "rss", "gallery", "widgets", "google analytics"]
min_version = "0.72"

[author]
  name = "Digitalcraftsman"
  homepage = "//github.com/digitalcraftsman"
authors = [
  {name = "Paul Canham", homepage = "https://github.com/pcanham"},
  {name = "Tory Anderson", homepage = "https://gitlab.com/toryanderson"},
  {name = "Digitalcraftsman", homepage = "https://github.com/digitalcraftsman"}
]

# If porting an existing theme
[original]
  name = "Ruipeng Zhang"
  homepage = "http://blog.zhangruipeng.me"
  repo = "https://github.com/ppoffice/hexo-theme-icarus"
